### ISSUE TITLE
Problem installing pymodbus

### ISSUE THREAD

**Issue by Renevandenbroek** [saidlm/Domoticz-Solax-plugin#14]
First of all, thank you for the plugin. 
I hope I can charge and discharge my battery in an easy way later.  But for now:
I have a pi 4 4gb running bookworm and domoticz in a docker.
I have python 3.11.2 and libpython 3.11 installed.
But I have a problem installing pymodbus. 
If I use your command " sudo pip3 install -U pymodbus"  I get the following response

`rene@raspberrypi:~$ sudo pip3 install -U pymodbus
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
`
Any idea how I should do it?
Best regards 
Rene

**Comment by saidlm** [comment]
Hi,
There are two possible ways how to deal with "externally-managed-environment" .
- You can install the module under same user which is used for running Domoticz
- You can switch off the functionality by the command: rm /usr/lib/python3.11/EXTERNALLY-MANAGED

For my Docker image I have chosen the second option. It works to me properly.

Martin

**Comment by Renevandenbroek** [comment]
Thank you Martin for you quick response.
Rene

**Comment by Renevandenbroek** [comment]
tnx
