### ISSUE TITLE
TCP-IP SOLAX

### ISSUE THREAD

**Issue by tracteur12** [saidlm/Domoticz-Solax-plugin#2]
Hello,

Use Modbus TCP-IP with LAN dongle didn't work. 
Do you ask to solax technical support if they can't to open a port for the next Update (LAN Dongle)?

Regard,

Romain BERNARD

**Comment by saidlm** [comment]
Hi,
I was in touch with the DZD Drazice. It is the company which sells Solax under their own brand in Czech Republic. I asked exactly for  that. Unfortunately the answer was that there is no plan to do that.

Martin
