### ISSUE TITLE
When will ability to control the inverter become available? 

### ISSUE THREAD

**Issue by averter** [saidlm/Domoticz-Solax-plugin#5]
This is a feature request. The project is meant to be able to both read and control the inverter via modbus, and so I wonder when will the ability to control it become available? Any plans, dates, thoughts? 
I think that they have a similar system already implemented in [home assistant](https://homeassistant-solax-modbus.readthedocs.io/en/latest/) but nothing for domoticz, and so this would definitely be unique/valuable :-). Thanks.

**Comment by saidlm** [comment]
Hi,
yes there is plan to add the this kind of functionality. I am thinking about variables such as operation mode, reserved battery capacity, charge battery discharge battery etc. I would like be able to change inverter mode base on current weather condition and forecast. The next possibility how to use it is when you are on spot market and you need to control your energy production.

The main issue which I am facing to is lack of documentation. Only documentation which I have is list of modbus registers. The configuration or at least its part is stored in EEPROM with limited write cycles. I am not sure which registers are in EEPROM and which ones in RAM or how the writes to EEPROM are managed.  I have already asked vendor for more information but have no success. I don't want to brick my inverter during tests :-(.

But anyway the answer is yes I have a plan to add this feature (at least part of  registers which are 'secure') during the summer but have no exact timeline for it.

Martin

**Comment by averter** [comment]
Wonderful to hear!
Regarding documentation, yes I'm sure the vendors wouldn't help much/share such information, but as mentioned before, others have probably already done some (if not all) of the work of reverse engineering the process. I've found the following webpages:

- [Solax Hybrid X1/X3 Inverter RealTime Data and control locally](https://community.openhab.org/t/solax-hybrid-x1-x3-inverter-realtime-data-and-control-locally/137371)
- [Modbus Power Control (remotecontrol power)](https://homeassistant-solax-modbus.readthedocs.io/en/stable/modbus-power-control/)

 I can't really tell if they are relevant or not :-), but am happy to search more as needed.

**Comment by saidlm** [comment]
I have just uploaded new version which is capable to control the inverter. The documentation will be updated in the near future as well.

Martin

**Comment by averter** [comment]
Fantastic. What version of python/pymodbus/domoticz are you using? I've updated to the latest versions but had errors even to read the values from the inverter, let alone writing them. Thanks.

**Comment by saidlm** [comment]
The current version of the plugin was tested with Domoticz version 2024.4, python 3.11.2, libpython 3.11 and pymodbus 3.6.8.

**Comment by averter** [comment]
Ahh, it works, thanks very much! FYI, if one uses the latest version of pymodbus 3.7.0 it won't work. I suspect it has to do with some change of the `ModbusTcpClient` function.
